"""Phase 1 discovery: log in, walk every surface, record the SPA's JSON traffic → docs/nexus_api_map.md.

Usage (local only, your own account):
    make connect      # once: sign in yourself in a visible browser; saves .discovery/storage_state.json
    make discover     # headless walk; or set NEXUS_EMAIL / NEXUS_PASSWORD to log in with the form

The written map is redacted (tokens, emails, phones, person-name fields, long strings truncated).
Full raw captures stay in apps/api/.discovery/ which is git-ignored.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
from collections import OrderedDict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from ..config import get_settings
from .adapters.base import SURFACE_SIGNATURE, iter_lists, score_list
from .session import CapturedResponse, NexusSession, browser, perform_login

ROOT = Path(__file__).resolve().parents[4]
OUT_MD = ROOT / "docs" / "nexus_api_map.md"
RAW_DIR = Path(__file__).resolve().parents[2] / ".discovery"
STATE_FILE = RAW_DIR / "storage_state.json"

PERSON_KEYS = re.compile(r"(email|phone|mobile|first_?name|last_?name|full_?name|student_?name|user_?name|"
                         r"roll|enrol|dob|address|avatar|photo|token|secret|password|cookie|session)", re.I)
EMAIL = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")
PHONE = re.compile(r"\+?\d[\d\s-]{8,}\d")
JWT = re.compile(r"eyJ[\w-]+\.[\w-]+\.[\w-]+")
UUIDISH = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I)
SAFE_HEADERS = {"accept", "content-type", "x-requested-with", "origin", "referer"}


def redact(v: Any, key: str = "", depth: int = 0) -> Any:
    if PERSON_KEYS.search(key):
        return "[redacted]"
    if isinstance(v, dict):
        return {k: redact(x, k, depth + 1) for k, x in list(v.items())[:25]}
    if isinstance(v, list):
        return [redact(x, key, depth + 1) for x in v[:2]] + (["…"] if len(v) > 2 else [])
    if isinstance(v, str):
        s = JWT.sub("[jwt]", EMAIL.sub("[email]", PHONE.sub("[phone]", v)))
        return s if len(s) <= 60 else s[:57] + "…"
    return v


def shape(v: Any, depth: int = 0) -> Any:
    if depth > 4:
        return "…"
    if isinstance(v, dict):
        return {k: shape(x, depth + 1) for k, x in list(v.items())[:30]}
    if isinstance(v, list):
        return [shape(v[0], depth + 1)] if v else []
    return type(v).__name__


def normalize_endpoint(url: str) -> str:
    p = urlsplit(url)
    path = UUIDISH.sub("{uuid}", p.path)
    path = re.sub(r"/\d{3,}(?=/|$)", "/{id}", path)
    return f"{p.scheme}://{p.netloc}{path}"


def guess_surface(body: Any) -> tuple[str, float] | None:
    best: tuple[str, float] | None = None
    for lst in iter_lists(body):
        for surface in SURFACE_SIGNATURE:
            s = score_list(lst, surface)
            if s >= 2.0 and (best is None or s > best[1]):
                best = (surface, s)
    return best


def auth_header_kind(headers: dict[str, str]) -> str:
    h = {k.lower(): v for k, v in headers.items()}
    if "authorization" in h:
        return "Authorization: " + h["authorization"].split(" ", 1)[0] + " <redacted>"
    for k in h:
        if "token" in k or "auth" in k:
            return f"{k}: <redacted>"
    return "cookies only"


def write_map(caps: list[tuple[str, CapturedResponse]], dom_notes: dict[str, str]) -> None:
    groups: OrderedDict[tuple[str, str], list[tuple[str, CapturedResponse]]] = OrderedDict()
    for page, c in caps:
        groups.setdefault((c.method, normalize_endpoint(c.url)), []).append((page, c))
    lines = [
        "# Nexus API map",
        "",
        f"_Generated by `python -m eztracker.scraper.discovery` on {datetime.now(UTC):%Y-%m-%d %H:%M UTC}. "
        "Values are redacted and truncated; full captures are in `apps/api/.discovery/` (git-ignored)._",
        "",
        "## Summary",
        "",
        "| Seen on page | Method | Endpoint | Status | Auth | Looks like |",
        "|---|---|---|---|---|---|",
    ]
    pins: dict[str, dict[str, Any]] = {}
    for (method, ep), items in groups.items():
        page, c = items[0]
        g = guess_surface(c.body)
        looks = f"{g[0]} ({g[1]:.1f})" if g else ""
        lines.append(f"| {page} | {method} | `{ep}` | {c.status} | {auth_header_kind(c.request_headers)} | {looks} |")
        if g and (g[0] not in pins or g[1] > pins[g[0]]["_score"]):
            pins[g[0]] = {"url_contains": urlsplit(ep).path.replace("{uuid}", "").rstrip("/"), "_score": g[1]}
    lines += ["", "## Endpoints", ""]
    for (method, ep), items in groups.items():
        page, c = items[0]
        hdrs = {k: v for k, v in c.request_headers.items() if k.lower() in SAFE_HEADERS}
        lines += [f"### `{method} {ep}`", "", f"- first seen on: `{page}` · calls: {len(items)} · status {c.status}",
                  f"- auth: {auth_header_kind(c.request_headers)}", f"- request headers (safe subset): `{hdrs}`", "",
                  "Response shape:", "", "```json", json.dumps(shape(c.body), indent=2)[:2500], "```", "",
                  "Sample (redacted):", "", "```json", json.dumps(redact(c.body), indent=2, default=str)[:2500],
                  "```", ""]
    lines += ["## DOM notes", ""] + [f"- **{k}**: {v}" for k, v in dom_notes.items()]
    lines += ["", "## Suggested pins (`apps/api/eztracker/scraper/endpoints.json`)", "", "```json",
              json.dumps({k: {"url_contains": v["url_contains"]} for k, v in pins.items()}, indent=2), "```", ""]
    OUT_MD.write_text("\n".join(lines))
    print(f"wrote {OUT_MD.relative_to(ROOT)} — {len(groups)} endpoints")


async def discover() -> None:
    settings = get_settings()
    RAW_DIR.mkdir(exist_ok=True)
    email, password = os.environ.get("NEXUS_EMAIL"), os.environ.get("NEXUS_PASSWORD")
    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else None
    caps: list[tuple[str, CapturedResponse]] = []
    dom_notes: dict[str, str] = {}
    async with browser() as b:
        ctx = await b.new_context(storage_state=state, locale="en-IN", timezone_id="Asia/Kolkata")
        page = await ctx.new_page()
        sess = NexusSession(ctx, page, settings.nexus_base_url)
        if state is None:
            if not (email and password):
                raise SystemExit("Run `make connect` first, or set NEXUS_EMAIL and NEXUS_PASSWORD in .env")
            await perform_login(page, settings.nexus_base_url, email, password)
            STATE_FILE.write_text(json.dumps(await ctx.storage_state()))

        async def visit(label: str, path: str, scroll: bool = True, tabs: list[str] | None = None) -> None:
            async with sess.capture() as bucket:
                await sess.goto(path)
                if scroll:
                    await sess.scroll_to_end()
                for t in tabs or []:
                    tab = page.get_by_role("tab", name=re.compile(rf"^{re.escape(t)}", re.I)).first
                    if await tab.count() == 0:
                        tab = page.get_by_text(re.compile(rf"^{re.escape(t)}\b", re.I)).first
                    if await tab.count():
                        await sess.polite_pause()
                        await tab.click()
                        await page.wait_for_load_state("networkidle")
                        await sess.scroll_to_end()
            caps.extend((label, c) for c in bucket)
            html = await page.content()
            (RAW_DIR / f"{label.replace('/', '_')}.html").write_text(html)
            dom_notes[label] = (f"url `{UUIDISH.sub('{uuid}', page.url)}`, "
                                f"{await page.locator('a[href*=\"/assignments/\"]').count()} assignment links, "
                                f"{await page.locator('[role=tab]').count()} role=tab elements, "
                                f"{len(bucket)} JSON responses")

        await visit("courses", "/student/lms/courses", tabs=["Pre-Term", "Term 1"])
        course_link = page.locator("a[href*='/student/lms/courses/']").first
        if await course_link.count():
            href = await course_link.get_attribute("href")
            if href:
                await visit("course-detail", href)
        await visit("my-work", "/student/lms/assignments", tabs=["Assignments", "Forms"])
        a_link = page.locator("a[href*='/student/lms/assignments/']").first
        if await a_link.count():
            href = await a_link.get_attribute("href")
            if href:
                await visit("assignment-detail", href, scroll=False)
        await visit("notifications", "/student/lms/notifications",
                    tabs=["Assignment", "Announcement", "Course Calendar", "General", "All"])
        first_item = page.locator("main li, main [role=listitem]").first
        if await first_item.count():
            async with sess.capture() as bucket:
                await sess.polite_pause()
                await first_item.click()
                await page.wait_for_load_state("networkidle")
            caps.extend(("notification-detail", c) for c in bucket)
        STATE_FILE.write_text(json.dumps(await ctx.storage_state()))
        await ctx.close()

    (RAW_DIR / "captures.json").write_text(json.dumps(
        [{"page": p, "url": c.url, "method": c.method, "status": c.status, "body": c.body} for p, c in caps],
        indent=1, default=str))
    write_map(caps, dom_notes)


if __name__ == "__main__":
    asyncio.run(discover())
